"""Production preflight for the authenticated, persistent web deployment."""
from __future__ import annotations

import os
import re
from collections.abc import Mapping


def validate_production(env: Mapping[str, str] | None = None) -> None:
    env = os.environ if env is None else env
    if env.get("ENVIRONMENT", "development").lower() != "production":
        return
    errors = []
    key = env.get("SENTINELIQ_INGEST_API_KEY", "")
    if len(key) < 32 or key.lower().startswith("change-me"):
        errors.append("SENTINELIQ_INGEST_API_KEY must be a generated secret of at least 32 characters")
    if not env.get("SENTINELIQ_DATABASE_URL"):
        errors.append("SENTINELIQ_DATABASE_URL is required")
    if not re.fullmatch(r"[a-zA-Z0-9_-]{1,64}", env.get("SENTINELIQ_USERNAME", "owner")):
        errors.append("SENTINELIQ_USERNAME must be a simple account name")
    if not re.fullmatch(r"\$2[aby]\$\d{2}\$[./A-Za-z0-9]{53}", env.get("SENTINELIQ_PASSWORD_HASH", "")):
        errors.append("SENTINELIQ_PASSWORD_HASH must be a bcrypt hash generated by caddy hash-password")
    if errors:
        raise RuntimeError("Production configuration rejected: " + "; ".join(errors))
